app/modules/admin/models/UserSearch.php
<?php

namespace app\modules\admin\models;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use app\models\User;

/**
 * UserSearch represents the model behind the search form of `app\models\User`.
 */
class UserSearch extends User
{
	public $full_name;
	public $sport_id;

	/**
	 * @inheritdoc
	 */
	public function rules()
	{
		return [
			[['id', 'status', 'sport_id'], 'integer'],
			[['username', 'email', 'full_name'], 'safe'],
		];
	}

	/**
	 * @inheritdoc
	 */
	public function scenarios()
	{
		// bypass scenarios() implementation in the parent class
		return Model::scenarios();
	}

	/**
	 * Creates data provider instance with search query applied
	 *
	 * @param array $params
	 *
	 * @return ActiveDataProvider
	 */
	public function search($params)
	{
		$query = User::find()->joinWith('sport');

		// add conditions that should always apply here

		$dataProvider = new ActiveDataProvider([
			'query' => $query,
			'sort' => [
				'attributes' => [
					'id',
					'status',
					'username',
					'email',
					'created_at',
					'full_name' => [
						'asc' => ['first_name' => SORT_ASC, 'last_name' => SORT_ASC],
						'desc' => ['first_name' => SORT_DESC, 'last_name' => SORT_DESC],
					],
				],
			],
		]);

		$this->load($params);

		if ( ! $this->validate()) {
			// uncomment the following line if you do not want to return any records when validation fails
			// $query->where('0=1');
			return $dataProvider;
		}

		// grid filtering conditions
		$query->andFilterWhere([
			'id'         => $this->id,
			'status'     => $this->status,
			'created_at' => $this->created_at,
            'sport.id'   => $this->sport_id,
		]);

		$query->andFilterWhere(['like', 'username', $this->username])
			->andFilterWhere(['like', 'email', $this->email])
			->andFilterWhere(['like', 'concat(first_name, " " , last_name) ', $this->full_name]);


		return $dataProvider;
	}
}

app/modules/admin/controllers/DashboardController.php
<?php

namespace app\modules\admin\controllers;

class DashboardController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	/**
	 * Displays dashboard with some statistics.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		return $this->render('index');
	}
}

app/modules/admin/controllers/SettingsController.php
<?php

namespace app\modules\admin\controllers;

/**
 * Class SettingsController
 *
 * @package app\modules\admin\controllers
 */
class SettingsController extends Controller
{
	/**
	* @inheritdoc
	*/
	public function actions()
	{
		return [
			'app' => [
				'class' => 'justcoded\yii2\settings\actions\SettingsAction',
				'modelClass' => 'justcoded\yii2\settings\forms\AppSettingsForm',
			],
		];
	}
}

app/modules/admin/controllers/UsersController.php
<?php

namespace app\modules\admin\controllers;

use app\models\Address;
use app\models\User;
use app\models\UserProfile;
use app\modules\admin\forms\UserForm;
use app\modules\admin\models\UserSearch;
use app\traits\controllers\FindModelOrFail;
use Yii;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
	use FindModelOrFail;
	
	/**
	 * @inheritdoc
	 */
	public function init()
	{
		parent::init();
		$this->modelClass = UserForm::class;
	}
	
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'verbs' => [
				'class'   => VerbFilter::class,
				'actions' => [
					'delete' => ['POST'],
				],
			],
		];
	}
	
	/**
	 * Lists all User models.
	 *
	 * @return mixed
	 */
	public function actionIndex()
	{
		$searchModel = new UserSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $address = new Address();

        if (Yii::$app->request->post('add'))
        {
            if ($address->load(Yii::$app->request->post()))
            {
                $address->save(false);
                return $this->redirect('users');
            }
        }
		
		return $this->render('index', [
			'searchModel'  => $searchModel,
			'dataProvider' => $dataProvider,
            'address'      => $address,
		]);
	}


	
	/**
	 * Creates a new User model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 *
	 * @return mixed
	 */
	public function actionCreate()
	{
		$model = new UserForm();
		$profile = new UserProfile();
		
		$model->on(User::EVENT_BEFORE_INSERT, function ($event) use ($model) {
            $model->setPassword($model->password);
            $model->generateAuthKey();
        });
		
		if (($model->load(Yii::$app->request->post()) && $model->save()) && ($profile->load(Yii::$app->request->post()) && $profile->save())) {
			return $this->redirect(['update', 'id' => $model->id]);
		}
		
		return $this->render('create', [
			'model' => $model,
            'profile' => $profile
		]);
	}
	
	/**
	 * Updates an existing User model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionUpdate($id)
	{

        if (Yii::$app->request->post('del')) {
            $this->actionDelete($id);
        }

		$model = $this->findModel($id);
		$profile = $model->userProfile ?? new UserProfile();
		
		if (($model->load(Yii::$app->request->post()) && $model->save()) && ($profile->load(Yii::$app->request->post()) && $profile->save())) {
			return $this->redirect(['update', 'id' => $model->id]);
		}

		return $this->render('update', [
			'model' => $model,
            'profile' => $profile,
		]);
	}
	
	/**
	 * Deletes an existing User model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 *
	 * @param integer $id
	 *
	 * @return mixed
	 */
	public function actionDelete($id)
	{
		$this->findModel($id)->delete();

		return $this->redirect(['index']);
	}
	
}

app/modules/admin/views/layouts/main.php
<?php
use dmstr\widgets\Alert;
use yii\widgets\Breadcrumbs;
use app\modules\admin\assets\AssetBundle;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;

/* @var $this \yii\web\View */
/* @var $content string */

AssetBundle::register($this);

$adminlteAssets = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');

$this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="<?= Yii::$app->charset ?>"/>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?= Html::csrfMetaTags() ?>
	<title><?= Html::encode($this->title) ?></title>
	<?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>

<div class="wrapper">

	<?= $this->render('../partials/header', ['adminlteAssets' => $adminlteAssets]); ?>

	<?= $this->render('../partials/nav', ['adminlteAssets' => $adminlteAssets]); ?>

	<div class="content-wrapper">
		<?= $this->render('../partials/content-header'); ?>

		<section class="content">
			<?= Alert::widget() ?>
			<?= $content ?>
		</section>
	</div>

	<?= $this->render('../partials/footer'); ?>
</div>
<!-- ./wrapper -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

app/modules/admin/views/partials/content-header.php
<?php
use dmstr\widgets\Alert;
use yii\widgets\Breadcrumbs;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use app\modules\admin\assets\ThemeHelper;

/* @var $this \yii\web\View */

?>

<?php if (! ThemeHelper::printBlock(ThemeHelper::BLOCK_CONTENT_HEADER)) : ?>
<section class="content-header">
	<h1>
		<?= Html::encode(ArrayHelper::getValue($this->params, 'heading', $this->title)) ?>
		<?php if (!empty($this->params['subheading'])) : ?>
			<small><?= Html::encode($this->params['subheading']); ?></small>
		<?php endif; ?>

		<?php ThemeHelper::printBlock(ThemeHelper::BLOCK_HEADER_BUTTONS); ?>
	</h1>

	<?= Breadcrumbs::widget([
		'homeLink' => [
			'label' => '<i class="fa fa-dashboard"></i> Dashboard',
			'url' => ['/admin/dashboard'],
			'encode' => false,
		],
		'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
	]) ?>
</section>
<?php endif; ?>

app/modules/admin/views/partials/footer.php
<footer class="main-footer">
	<strong>&copy; 2017 My Company</strong>. All rights reserved.
</footer>

app/modules/admin/views/partials/header.php
<?php

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

	<?= Html::a('<span class="logo-mini">APP</span><span class="logo-lg">' . Yii::$app->name . '</span>',
		Yii::$app->homeUrl, ['class' => 'logo']) ?>

	<nav class="navbar navbar-static-top" role="navigation">

		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>

		<div class="navbar-custom-menu">

			<ul class="nav navbar-nav">

				<!-- Messages: style can be found in dropdown.less-->
				<li class="dropdown messages-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-envelope-o"></i>
						<span class="label label-success">4</span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have 4 messages</li>
						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">
								<li><!-- start message -->
									<a href="#">
										<div class="pull-left">
											<img src="<?= $adminlteAssets ?>/img/user2-160x160.jpg" class="img-circle"
												 alt="User Image"/>
										</div>
										<h4>
											Support Team
											<small><i class="fa fa-clock-o"></i> 5 mins</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>
								<!-- end message -->
								<li>
									<a href="#">
										<div class="pull-left">
											<img src="<?= $adminlteAssets ?>/img/user3-128x128.jpg" class="img-circle"
												 alt="user image"/>
										</div>
										<h4>
											AdminLTE Design Team
											<small><i class="fa fa-clock-o"></i> 2 hours</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>
								<li>
									<a href="#">
										<div class="pull-left">
											<img src="<?= $adminlteAssets ?>/img/user4-128x128.jpg" class="img-circle"
												 alt="user image"/>
										</div>
										<h4>
											Developers
											<small><i class="fa fa-clock-o"></i> Today</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>
								<li>
									<a href="#">
										<div class="pull-left">
											<img src="<?= $adminlteAssets ?>/img/user3-128x128.jpg" class="img-circle"
												 alt="user image"/>
										</div>
										<h4>
											Sales Department
											<small><i class="fa fa-clock-o"></i> Yesterday</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>
								<li>
									<a href="#">
										<div class="pull-left">
											<img src="<?= $adminlteAssets ?>/img/user4-128x128.jpg" class="img-circle"
												 alt="user image"/>
										</div>
										<h4>
											Reviewers
											<small><i class="fa fa-clock-o"></i> 2 days</small>
										</h4>
										<p>Why not buy a new awesome theme?</p>
									</a>
								</li>
							</ul>
						</li>
						<li class="footer"><a href="#">See All Messages</a></li>
					</ul>
				</li>
				<li class="dropdown notifications-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-bell-o"></i>
						<span class="label label-warning">10</span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have 10 notifications</li>
						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">
								<li>
									<a href="#">
										<i class="fa fa-users text-aqua"></i> 5 new members joined today
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-warning text-yellow"></i> Very long description here that may
										not fit into the page and may cause design problems
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-users text-red"></i> 5 new members joined
									</a>
								</li>

								<li>
									<a href="#">
										<i class="fa fa-shopping-cart text-green"></i> 25 sales made
									</a>
								</li>
								<li>
									<a href="#">
										<i class="fa fa-user text-red"></i> You changed your username
									</a>
								</li>
							</ul>
						</li>
						<li class="footer"><a href="#">View all</a></li>
					</ul>
				</li>
				<!-- Tasks: style can be found in dropdown.less -->
				<li class="dropdown tasks-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<i class="fa fa-flag-o"></i>
						<span class="label label-danger">9</span>
					</a>
					<ul class="dropdown-menu">
						<li class="header">You have 9 tasks</li>
						<li>
							<!-- inner menu: contains the actual data -->
							<ul class="menu">
								<li><!-- Task item -->
									<a href="#">
										<h3>
											Design some buttons
											<small class="pull-right">20%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-aqua" style="width: 20%"
												 role="progressbar" aria-valuenow="20" aria-valuemin="0"
												 aria-valuemax="100">
												<span class="sr-only">20% Complete</span>
											</div>
										</div>
									</a>
								</li>
								<!-- end task item -->
								<li><!-- Task item -->
									<a href="#">
										<h3>
											Create a nice theme
											<small class="pull-right">40%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-green" style="width: 40%"
												 role="progressbar" aria-valuenow="20" aria-valuemin="0"
												 aria-valuemax="100">
												<span class="sr-only">40% Complete</span>
											</div>
										</div>
									</a>
								</li>
								<!-- end task item -->
								<li><!-- Task item -->
									<a href="#">
										<h3>
											Some task I need to do
											<small class="pull-right">60%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-red" style="width: 60%"
												 role="progressbar" aria-valuenow="20" aria-valuemin="0"
												 aria-valuemax="100">
												<span class="sr-only">60% Complete</span>
											</div>
										</div>
									</a>
								</li>
								<!-- end task item -->
								<li><!-- Task item -->
									<a href="#">
										<h3>
											Make beautiful transitions
											<small class="pull-right">80%</small>
										</h3>
										<div class="progress xs">
											<div class="progress-bar progress-bar-yellow" style="width: 80%"
												 role="progressbar" aria-valuenow="20" aria-valuemin="0"
												 aria-valuemax="100">
												<span class="sr-only">80% Complete</span>
											</div>
										</div>
									</a>
								</li>
								<!-- end task item -->
							</ul>
						</li>
						<li class="footer">
							<a href="#">View all tasks</a>
						</li>
					</ul>
				</li>
				<!-- User Account: style can be found in dropdown.less -->

				<li class="dropdown user user-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<img src="<?= $adminlteAssets ?>/img/user2-160x160.jpg" class="user-image" alt="User Image"/>
						<span class="hidden-xs"><?= Html::encode(Yii::$app->user->identity->username) ?></span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header">
							<img src="<?= $adminlteAssets ?>/img/user2-160x160.jpg" class="img-circle"
								 alt="User Image"/>

							<p>
								<?= Html::encode(Yii::$app->user->identity->username) ?>
								<small>Member since Nov. 2012</small>
							</p>
						</li>
						<!-- Menu Body -->
						<li class="user-body">
							<div class="col-xs-4 text-center">
								<a href="#">Followers</a>
							</div>
							<div class="col-xs-4 text-center">
								<a href="#">Sales</a>
							</div>
							<div class="col-xs-4 text-center">
								<a href="#">Friends</a>
							</div>
						</li>
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-left">
								<a href="#" class="btn btn-default btn-flat">Profile</a>
							</div>
							<div class="pull-right">
								<?= Html::a(
									'Sign out',
									['/auth/logout'],
									['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
								) ?>
							</div>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

app/modules/admin/views/partials/nav.php
<aside class="main-sidebar">

	<section class="sidebar">

		<?= dmstr\widgets\Menu::widget(
			[
				'options' => ['class' => 'sidebar-menu', 'data-widget' => 'tree',],
				'items'   => [
					['label' => 'MAIN NAVIGATION', 'options' => ['class' => 'header']],
					['label' => 'Dashboard', 'icon' => 'dashboard', 'url' => ['/admin/dashboard']],
					['label' => 'Users',
					 	'icon' => 'users',
					 	'url' => ['/admin/users'],
					 	'active' => 'users' === Yii::$app->controller->id,
					],
                    ['label' => 'Personal Information', 'url' => ['/site/index']],
                    ['label' => 'Training Places', 'url' => ['/site/index']],
                    [
                        'label' => 'Sport',
                        'icon'  =>  'sport',
                        'url'   => '#',
                        'items' => [
                            ['label' => 'Boxing', 'url' => ['#']],
                            ['label' => 'Tennis', 'url' => ['#']],
                            ['label' => 'Swimming', 'url' => ['#']],
                        ],
                    ],
					['label' => 'Permissions',
					 'icon' => 'lock',
					 'url' => ['/admin/rbac/permissions'],
					 'active' => 'permissions' === Yii::$app->controller->id,
					],
					[
						'label' => 'Settings',
						'icon'  =>  'gears',
						'url'   => '#',
						'items' => [
							['label' => 'App', 'url' => ['/admin/settings/app']],
						],
					],
					[
						'label' => 'Drop example',
						'icon'  => 'share',
						'url'   => '#',
						'items' => [
							['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii'],],
							['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug'],],
							[
								'label' => 'Level One',
								'icon'  => 'circle-o',
								'url'   => '#',
								'items' => [
									['label' => 'Level Two', 'icon' => 'circle-o', 'url' => '#',],
									[
										'label' => 'Level Two',
										'icon'  => 'circle-o',
										'url'   => '#',
										'items' => [
											['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
											['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
										],
									],
								],
							],
						],
					],
				],
			]
		) ?>

	</section>

</aside>

app/modules/admin/views/settings/app.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model justcoded\yii2\settings\forms\SettingsForm */

$this->title                   = 'App settings';
$this->params['breadcrumbs'][] = $this->title;
$this->params['heading']       = 'Settings';
$this->params['subheading']    = 'App';

?>
	
<div class="user-form box">

	<?php $form = ActiveForm::begin([
		'layout' => 'horizontal',
	]); ?>
	
	<?= Html::errorSummary($model); ?>
		
		<div class="box-body">
			<h4 class="col-md-offset-1">Admin Email</h4>
			<?= $form->field($model, 'adminName')->textInput()->label('Name') ?>
			<?= $form->field($model, 'adminEmail')->textInput()->label('Email') ?>

			<h4 class="col-md-offset-1">System Email</h4>
			<?= $form->field($model, 'systemName')->textInput()->label('Name') ?>
			<?= $form->field($model, 'systemEmail')->textInput()->label('Email') ?>

			<h4 class="col-md-offset-1">Authentication</h4>
			<?= $form->field($model, 'passwordResetToken')->input('number') ?>
			<?= $form->field($model, 'rememberMeExpiration')->input('number') ?>
		</div>
		<div class="box-footer text-right">
			<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
		</div>
	
	<?php ActiveForm::end(); ?>
</div>

app/modules/admin/views/users/_form.php
<?php

use app\models\User;
use app\models\UserProfile;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use app\models\Sport;
use yii\helpers\ArrayHelper;

/**
 * @var $this yii\web\View
 * @var $model \app\modules\admin\forms\UserForm
 * @var $profile \app\models\UserProfile$
 * @var $form yii\widgets\ActiveForm
 */
?>

<div class="user-form box">
	
	<?php $form = ActiveForm::begin([
		'layout' => 'horizontal',
	]); ?>

	<div class="box-body">
		<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
		
		<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
		
		<?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
		
		<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
		
		<?= $form->field($model, 'password')->passwordInput() ?>
		
		<?= $form->field($model, 'passwordRepeat')->passwordInput() ?>

		<?= $form->field($profile, 'birthdate')->textInput() ?>
		<?= $form->field($profile, 'about')->textarea() ?>
		<?= $form->field($profile, 'sport_id')->dropDownList(ArrayHelper::map(Sport::find()->asArray()->all(), 'id', 'title')) ?>
		<?= $form->field($profile, 'sport_title')->textInput() ?>
		<?= $form->field($profile, 'personal_bests')->textarea() ?>
		<?= $form->field($profile, 'coach_name')->textInput() ?>
		<?= $form->field($profile, 'photo_filename')->textInput() ?>
		<?= $form->field($profile, 'facebook')->textInput() ?>
		<?= $form->field($profile, 'twitter')->textInput() ?>
		<?= $form->field($profile, 'instagram')->textInput() ?>

		<?= $form->field($model, 'status')->dropDownList(User::getStatusesList()) ?>
		
		<?= $form->field($model, 'roles')->dropDownList(User::getRolesList(), [
			'multiple' => 'multiple',
		]) ?>
	</div>
	<div class="box-footer text-right">
		<?= Html::submitButton($model->isNewRecord ? 'Save' : 'Update', ['class' => 'btn btn-success']) ?>

        <?php
            if (Yii::$app->controller->action->id == 'update')
            {
                echo Html::submitButton('Del', ['class' => 'btn btn-danger', 'name' => 'del', 'value' => 1]);
            }
        ?>
	</div>
	
	<?php ActiveForm::end(); ?>
</div>

app/modules/admin/views/users/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\modules\admin\forms\UserForm */

$this->title                   = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$this->params['heading']       = 'Users';
$this->params['subheading']    = 'Add New';
?>
<div class="user-create">

	<?= $this->render('_form', [
		'model' => $model,
        'profile' => $profile
	]) ?>

</div>

app/modules/admin/views/users/index.php
<?php

use app\models\Address;
use yii\bootstrap\Tabs;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = 'Users';
$this->params['breadcrumbs'][] = $this->title;

?>

<?php
    echo Tabs::widget([
    'items' => [
        [
            'label' => 'Personal Information',
            'content' => $this->render('tabs/personal', [
                'searchModel'  => $searchModel,
                'dataProvider' => $dataProvider,
            ]),
            'active' => true,
        ],

        [
            'label' => 'Training Places',
            'content' => $this->render('tabs/training', [
                'address' => $address
            ]),
        ],
    ],
]);
?>

app/modules/admin/views/users/tabs/personal.php
<?php

use app\models\User;
use app\modules\admin\widgets\LinkedColumn;
use yii\helpers\Html;
use app\modules\admin\assets\ThemeHelper;
use app\modules\admin\widgets\BoxGridView;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title                   = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>



<div class="user-index">
    <?php $this->beginBlock(ThemeHelper::BLOCK_HEADER_BUTTONS); ?>
        <?= Html::a('Add New', ['create'], ['class' => 'btn btn-sm btn-success']) ?>
    <?php $this->endBlock(); ?>

    <?= BoxGridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel'  => $searchModel,
        'columns'      => [
            [
                'header' => '#', 
                'content' => function ($model, $key, $index, $column) { 
                    $pagination = $column->grid->dataProvider->getPagination();
                    $index = $pagination !== false
                        ? $pagination->getOffset() + $index + 1
                        : $index + 1;
                        
                    return Html::a($index, ['users/update', 'id' => $model->id]);
                }
            ],
            [
                'class' => LinkedColumn::class,
                'header' => 'Name',
                'attribute' => 'full_name',
                'value' => 'fullName',
            ],
            'username',
            'email',
            array(
                'attribute' => 'status',
                'value' => 'statusAlias',
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'status',
                    User::getStatusesList(),
                    ['prompt' => 'All', 'class' => 'form-control']
                ),
            ),
            'created_at:date:Registered',
            // 'updated_at',
            [
                'attribute' => 'sport.title',
                'label' => 'Sport',
                'filter' => Html::activeDropDownList(
                    $searchModel,
                    'sport_id',
                    \app\models\Sport::find()->select(['title'])->indexBy('id')->column(),
                    ['prompt' => 'All', 'class' => 'form-control']
                ),
            ],
        ],
    ]); ?>

</div>

app/modules/admin/views/users/tabs/training.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

$addForm = ActiveForm::begin();

    echo $addForm->field($address, "title")->label();

    echo $addForm->field($address, "title")->label();

    echo $addForm->field($address, "line1")->label();

    echo $addForm->field($address, "line2")->label();

    echo $addForm->field($address, "city")->label();

    echo $addForm->field($address, "state")->label();

    echo $addForm->field($address, "country")->label();

    echo $addForm->field($address, "postal_code")->label();

    echo $addForm->field($address, "postal_code")->label();

    echo Html::submitButton('Add', [
        'class' => 'btn btn-default',
        'name' => 'add',
        'value' => 1
    ]);


ActiveForm::end();

app/modules/admin/views/users/update.php
<?php

/* @var $this yii\web\View */
/* @var $model \app\modules\admin\forms\UserForm */
/* @var $roles array */

$this->title = "Update {$model->fullName}";
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->fullName, 'url' => ['update', 'id' => $model->id]];
$this->params['heading'] = 'Users';
$this->params['subheading'] = $model->fullName;
?>
<div class="user-update">
	
	<?= $this->render('_form', [
		'model' => $model,
		'profile' => $profile,
	]) ?>

</div>