app/controllers/AuthController.php
<?php

namespace app\controllers;

use app\forms\RegisterForm;
use app\models\helpers\SignupService;
use Yii;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\forms\LoginForm;
use app\forms\PasswordRequestForm;
use app\forms\PasswordUpdateForm;
use app\models\User;

class AuthController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::class,
				'only'  => ['logout'],
				'rules' => [
					[
						'actions' => ['logout'],
						'allow'   => true,
						'roles'   => ['@'],
					],
				],
			],
			'verbs'  => [
				'class'   => VerbFilter::class,
				'actions' => [
					'logout' => ['get'],
				],
			],
		];
	}

	/**
	 * Login action.
	 *
	 * @return Response|string
	 */
	public function actionLogin()
	{
		if (! Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();

        if ($model->load(Yii::$app->request->post())) {
            try{
                if($model->login()){
                    return $this->goBack();
                }
            } catch (\DomainException $e){
                Yii::$app->session->setFlash('error', $e->getMessage());
                return $this->goHome();
            }
        }

		return $this->render('login', [
			'model' => $model,
		]);
	}

	/**
	 * Logout action.
	 *
	 * @return Response
	 */
	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	/**
	 * Register action.
	 *
	 * @return string|Response
	 */
	public function actionRegister()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new RegisterForm();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $signupService = new SignupService();

			try
            {
                $user = $signupService->signup($model);
                Yii::$app->session->setFlash('success', 'Check your email to confirm the registration.');
                $signupService->sentEmailConfirm($user);
                return $this->goHome();
            } catch (\RuntimeException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
		}

		return $this->render('register', [
			'model' => $model,
		]);
	}

	/**
	 * Password request action
	 *
	 * @return string|Response
	 */
	public function actionPasswordRequest()
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new PasswordRequestForm();

		if ($model->load(Yii::$app->request->post()) && $model->request()) {
			Yii::$app->session->addFlash(
				'success',
				'If the email address is registered in the system, we would send a letter there shortly.'
			);

			return $this->goBack();
		}

		return $this->render('password-request', [
			'model' => $model,
		]);
	}

	/**
	 * Password update action
	 *
	 * @param string $token Password reset token.
	 *
	 * @return string|Response
	 * @throws NotFoundHttpException If token not found in DB.
	 */
	public function actionPasswordUpdate($token)
	{
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		if (!User::isPasswordResetTokenValid($token)) {
			throw new NotFoundHttpException('Page not found.');
		}

		$model = new PasswordUpdateForm();
		$model->resetToken = $token;

		if ($model->load(Yii::$app->request->post()) && $model->update()) {
			Yii::$app->session->addFlash('success', 'Your password has been successfully updated!');

			return $this->goBack();
		}

		return $this->render('password-update', [
			'model' => $model,
		]);
	}

}

app/controllers/ProfileController.php
<?php

namespace app\controllers;


use app\models\Sport;
use Yii;
use app\models\UserProfile;
use yii\web\UploadedFile;

class ProfileController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{

	    $model = $this->findOrCreateModel(Yii::$app->user->id);

	    if (Yii::$app->request->post('save') && $model->load(Yii::$app->request->post()))
        {
            if (null !== $model->sport_title)
            {
                $sport = Sport::findOne($model->sport_id);
                $model->sport_title = $sport->title;
            }


            if ($image = UploadedFile::getInstance($model, 'photo_filename'))
            {
                $imageName = md5(time()) . '.' . $image->getExtension();
                $savePath = Yii::getAlias('@webroot/img/') . $imageName;
                $image->saveAs($savePath);
                $model->photo_filename = $imageName;
            }

            $model->save(false);
        }

        return $this->render('index', [
            'model' => $model,
        ]);
	}

	public function findOrCreateModel($id)
    {
        if (null !== $model = UserProfile::find()->where(['user_id' => $id])->one()) {
            return $model;
        } else {
            $model = new UserProfile();
            $model->user_id = $id;
            return $model;
        }

    }

}

app/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\helpers\SignupService;
use app\models\Sport;
use app\models\User;
use app\models\UserProfile;
use Yii;
use yii\web\Response;
use app\forms\ContactForm;

class SiteController extends Controller
{
	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{

	    $users = User::find()->asArray()->with('sport')->all();


		return $this->render('index');
	}

	/**
	 * Displays contact page.
	 *
	 * @return Response|string
	 */
	public function actionContact()
	{
		$model = new ContactForm();
		if ($model->load(Yii::$app->request->post()) && $model->contact()) {
			Yii::$app->session->setFlash('contactFormSubmitted');

			return $this->refresh();
		}

		return $this->render('contact', [
			'model' => $model,
		]);
	}

	/**
	 * Displays about page.
	 *
	 * @return string
	 */
	public function actionAbout()
	{
		return $this->render('about');
	}

    public function actionAthletes()
    {
        $athletes = UserProfile::find()->all();
        $sports = Sport::find()->all();

        return $this->render('athletes', [
            'athletes' => $athletes,
            'sports' => $sports,
        ]);
    }

    public function actionAthlete($id)
    {
        $model = UserProfile::find()->where(['user_id' => $id])->one();

        return $this->render('athlete', [
            'athlete' => $model
        ]);
    }

    public function actionSignupConfirm($token)
    {
        $signupService = new SignupService();

        try{
            $signupService->confirmation($token);
            Yii::$app->session->setFlash('success', 'You have successfully confirmed your registration.');
        } catch (\Exception $e){
            Yii::$app->errorHandler->logException($e);
            Yii::$app->session->setFlash('error', $e->getMessage());
        }

        return $this->goHome();
    }
}

app/views/partials/footer.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

?>

<footer>
    <div class="uk-container uk-container-center">
        <div class="uk-child-width-1-2@s" uk-grid>
            <div class="uk-margin-large-top uk-margin-large-bottom">
                <h2>Plato</h2>
                <p>Plato business company, Inc.<br>
                    4455 Great building Ave, Suite A10<br>
                    San Francisco, CA 94107<br>
                    P: (123) 456-7890 </p>
            </div>
            <div class="uk-margin-large-top uk-margin-large-bottom">
                <div class="uk-child-width-1-2@s" uk-grid>
                    <div>
                        <h2>Browse pages</h2>
                        <p>Lorem ipsum dolor sit amet</p>
                        <p>Tamquam ponderum at eum, nibh dicta offendit mei</p>
                        <p>Vix no vidisse dolores intellegam</p>
                        <p>Est virtute feugiat accommodare eu</p>
                    </div>
                    <div>
                        <h2>Keep updated</h2>
                        <p>Enter your email to subcribe newsletter </p>
                        <form>
                            <div class="uk-margin">
                                <div class="uk-inline">
                                    <a class="uk-form-icon uk-form-icon-flip" href="#" uk-icon="icon: pencil"></a>
                                    <input class="uk-input" type="text">
                                </div>
                            </div>
                        </form>
                        <div class="social_icons">
                            <a class="uk-margin-small-right" href="#" uk-icon="icon: facebook"></a>
                            <a class="uk-margin-small-right" href="#" uk-icon="icon: twitter"></a>
                            <a class="uk-margin-small-right" href="#" uk-icon="icon: linkedin"></a>
                            <a class="uk-margin-small-right" href="#" uk-icon="icon: pinterest"></a>
                            <a class="uk-margin-small-right" href="#" uk-icon="icon: google-plus"></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/partials/header.php
<?php

use yii\helpers\Html;

?>

<header>
    <div class="uk-container">
        <nav uk-navbar>

            <div class="uk-navbar-left">

                <ul class="uk-navbar-nav">
                    <li><?=Html::a('Home',['site/index'], ['class' => 'uk-padding-remove-left'])?></li>
                    <li><?=Html::a('Athletes', ['site/athletes'])?></li>
                    <li><?=Html::a('About us', ['site/about'])?></li>
                    <li><?=Html::a('Contact', ['site/contact'])?></li>
                </ul>

            </div>

            <div class="uk-navbar-right">

                <ul class="uk-navbar-nav">
                    <?php if(Yii::$app->user->isGuest):?>
                        <li><?=Html::a('Login', ['auth/login'])?></li>
                        <li><?=Html::a('Register', ['auth/register'])?></li>
                    <?php else:?>
                        <li><?=Html::a('Profile', ['profile/index'])?></li>
                        <li><?=Html::a('Logout', ['auth/logout'])?></li>
                    <?php endif;?>
                </ul>

            </div>

        </nav>
    </div>
</header>